#Powerful quotes & sayings about life

quotes_teletips = [
"rebo = https://github.com/Sinan-M-116/DATE_TIME_USERBOT.",
"Change the world by being yourself.",
"Every moment is a fresh beginning.",
"Never regret anything that made you smile.",
"rebo = https://github.com/Sinan-M-116/DATE_TIME_USERBOT.",
"Tough times never last but tough people do.",
"Problems are not stop signs, they are guidelines.",
"Have enough courage to start and enough heart to finish.",
"I could agree with you but then we’d both be wrong.",
"Oh, the things you can find, if you don’t stay behind.",
"Determine your priorities and focus on them.",
"Be so good they can’t ignore you.",
"Yesterday you said tomorrow. Just do it.",
"I don’t need it to be easy, I need it to be worth it.",
"Never let your emotions overpower your intelligence.",
"rebo = https://github.com/Sinan-M-116/DATE_TIME_USERBOT.",
"rebo = https://github.com/Sinan-M-116/DATE_TIME_USERBOT.",
"Don’t you know your imperfections is a blessing?",
"Reality is wrong, dreams are for real.",
"rebo = https://github.com/Sinan-M-116/DATE_TIME_USERBOT.",
"The time is always right to do what is right.",
"Let the beauty of what you love be what you do.",
"May your choices reflect your hopes, not your fears.",
"A happy soul is the best shield for a cruel world.",
"rebo = https://github.com/Sinan-M-116/DATE_TIME_USERBOT.",
"White is not always light and black is not always dark.",
"Happiness depends upon ourselves.",
"Turn your wounds into wisdom.",
"rebo = https://github.com/Sinan-M-116/DATE_TIME_USERBOT.",
"I will remember and recover, not forgive and forget.",
"Embrace the glorious mess that you are.",
"I have nothing to lose but something to gain."
]
